name: CI

on:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: luizm/action-sh-checker@v0.10.0
              with:
                  sh_checker_exclude: node_modules
    publish:
        if: github.ref == 'refs/heads/main'
        needs: ci
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v7
            - uses: voidzero-dev/setup-vp@v1.21.1
              with:
                  node-version-file: '.node-version'
                  run-install: false
            - run: ./bin/publish-package.sh
